$.get("http://NicoleMann.github.io/GitHub/partials/nav.html",function(data){
    $(document).ready(function(){
        $(".container").prepend(data);
        $(".container").fadeIn();
    });
});
$.get("http://NicoleMann.github.io/GitHub/partials/footer.html",function(data){
    $(document).ready(function(){
        $(".container").append(data);
        $(".container").fadeIn();
    });
});